/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_FrameOnly */

#ifndef _Included_apple_laf_JRSUIConstants_FrameOnly
#define _Included_apple_laf_JRSUIConstants_FrameOnly
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_FrameOnly_SHIFT
#define apple_laf_JRSUIConstants_FrameOnly_SHIFT 34L
#undef apple_laf_JRSUIConstants_FrameOnly_SIZE
#define apple_laf_JRSUIConstants_FrameOnly_SIZE 1L
#undef apple_laf_JRSUIConstants_FrameOnly_MASK
#define apple_laf_JRSUIConstants_FrameOnly_MASK 17179869184LL
#undef apple_laf_JRSUIConstants_FrameOnly__no
#define apple_laf_JRSUIConstants_FrameOnly__no 0L
#undef apple_laf_JRSUIConstants_FrameOnly__yes
#define apple_laf_JRSUIConstants_FrameOnly__yes 1L
#ifdef __cplusplus
}
#endif
#endif
