/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_Orientation */

#ifndef _Included_apple_laf_JRSUIConstants_Orientation
#define _Included_apple_laf_JRSUIConstants_Orientation
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_Orientation_SHIFT
#define apple_laf_JRSUIConstants_Orientation_SHIFT 11L
#undef apple_laf_JRSUIConstants_Orientation_SIZE
#define apple_laf_JRSUIConstants_Orientation_SIZE 2L
#undef apple_laf_JRSUIConstants_Orientation_MASK
#define apple_laf_JRSUIConstants_Orientation_MASK 6144LL
#undef apple_laf_JRSUIConstants_Orientation__horizontal
#define apple_laf_JRSUIConstants_Orientation__horizontal 1L
#undef apple_laf_JRSUIConstants_Orientation__vertical
#define apple_laf_JRSUIConstants_Orientation__vertical 2L
#ifdef __cplusplus
}
#endif
#endif
