/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_Focused */

#ifndef _Included_apple_laf_JRSUIConstants_Focused
#define _Included_apple_laf_JRSUIConstants_Focused
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_Focused_SHIFT
#define apple_laf_JRSUIConstants_Focused_SHIFT 30L
#undef apple_laf_JRSUIConstants_Focused_SIZE
#define apple_laf_JRSUIConstants_Focused_SIZE 1L
#undef apple_laf_JRSUIConstants_Focused_MASK
#define apple_laf_JRSUIConstants_Focused_MASK 1073741824LL
#undef apple_laf_JRSUIConstants_Focused__no
#define apple_laf_JRSUIConstants_Focused__no 0L
#undef apple_laf_JRSUIConstants_Focused__yes
#define apple_laf_JRSUIConstants_Focused__yes 1L
#ifdef __cplusplus
}
#endif
#endif
