/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_BooleanValue */

#ifndef _Included_apple_laf_JRSUIConstants_BooleanValue
#define _Included_apple_laf_JRSUIConstants_BooleanValue
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_BooleanValue_SHIFT
#define apple_laf_JRSUIConstants_BooleanValue_SHIFT 41L
#undef apple_laf_JRSUIConstants_BooleanValue_SIZE
#define apple_laf_JRSUIConstants_BooleanValue_SIZE 1L
#undef apple_laf_JRSUIConstants_BooleanValue_MASK
#define apple_laf_JRSUIConstants_BooleanValue_MASK 2199023255552LL
#undef apple_laf_JRSUIConstants_BooleanValue__no
#define apple_laf_JRSUIConstants_BooleanValue__no 0L
#undef apple_laf_JRSUIConstants_BooleanValue__yes
#define apple_laf_JRSUIConstants_BooleanValue__yes 1L
#ifdef __cplusplus
}
#endif
#endif
