/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_State */

#ifndef _Included_apple_laf_JRSUIConstants_State
#define _Included_apple_laf_JRSUIConstants_State
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_State_SHIFT
#define apple_laf_JRSUIConstants_State_SHIFT 3L
#undef apple_laf_JRSUIConstants_State_SIZE
#define apple_laf_JRSUIConstants_State_SIZE 4L
#undef apple_laf_JRSUIConstants_State_MASK
#define apple_laf_JRSUIConstants_State_MASK 120LL
#undef apple_laf_JRSUIConstants_State__active
#define apple_laf_JRSUIConstants_State__active 1L
#undef apple_laf_JRSUIConstants_State__inactive
#define apple_laf_JRSUIConstants_State__inactive 2L
#undef apple_laf_JRSUIConstants_State__disabled
#define apple_laf_JRSUIConstants_State__disabled 3L
#undef apple_laf_JRSUIConstants_State__pressed
#define apple_laf_JRSUIConstants_State__pressed 4L
#undef apple_laf_JRSUIConstants_State__pulsed
#define apple_laf_JRSUIConstants_State__pulsed 5L
#undef apple_laf_JRSUIConstants_State__rollover
#define apple_laf_JRSUIConstants_State__rollover 6L
#undef apple_laf_JRSUIConstants_State__drag
#define apple_laf_JRSUIConstants_State__drag 7L
#ifdef __cplusplus
}
#endif
#endif
