/* IKVM: copied from javac output and edited to remove i64 suffix *//* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_AlignmentVertical */

#ifndef _Included_apple_laf_JRSUIConstants_AlignmentVertical
#define _Included_apple_laf_JRSUIConstants_AlignmentVertical
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_AlignmentVertical_SHIFT
#define apple_laf_JRSUIConstants_AlignmentVertical_SHIFT 13L
#undef apple_laf_JRSUIConstants_AlignmentVertical_SIZE
#define apple_laf_JRSUIConstants_AlignmentVertical_SIZE 2L
#undef apple_laf_JRSUIConstants_AlignmentVertical_MASK
#define apple_laf_JRSUIConstants_AlignmentVertical_MASK 24576LL
#undef apple_laf_JRSUIConstants_AlignmentVertical__top
#define apple_laf_JRSUIConstants_AlignmentVertical__top 1L
#undef apple_laf_JRSUIConstants_AlignmentVertical__center
#define apple_laf_JRSUIConstants_AlignmentVertical__center 2L
#undef apple_laf_JRSUIConstants_AlignmentVertical__bottom
#define apple_laf_JRSUIConstants_AlignmentVertical__bottom 3L
#ifdef __cplusplus
}
#endif
#endif
