/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_IndicatorOnly */

#ifndef _Included_apple_laf_JRSUIConstants_IndicatorOnly
#define _Included_apple_laf_JRSUIConstants_IndicatorOnly
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_IndicatorOnly_SHIFT
#define apple_laf_JRSUIConstants_IndicatorOnly_SHIFT 31L
#undef apple_laf_JRSUIConstants_IndicatorOnly_SIZE
#define apple_laf_JRSUIConstants_IndicatorOnly_SIZE 1L
#undef apple_laf_JRSUIConstants_IndicatorOnly_MASK
#define apple_laf_JRSUIConstants_IndicatorOnly_MASK 2147483648LL
#undef apple_laf_JRSUIConstants_IndicatorOnly__no
#define apple_laf_JRSUIConstants_IndicatorOnly__no 0L
#undef apple_laf_JRSUIConstants_IndicatorOnly__yes
#define apple_laf_JRSUIConstants_IndicatorOnly__yes 1L
#ifdef __cplusplus
}
#endif
#endif
