/* IKVM: copied from javac output and edited to remove i64 suffix */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_Size */

#ifndef _Included_apple_laf_JRSUIConstants_Size
#define _Included_apple_laf_JRSUIConstants_Size
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_Size_SHIFT
#define apple_laf_JRSUIConstants_Size_SHIFT 0L
#undef apple_laf_JRSUIConstants_Size_SIZE
#define apple_laf_JRSUIConstants_Size_SIZE 3L
#undef apple_laf_JRSUIConstants_Size_MASK
#define apple_laf_JRSUIConstants_Size_MASK 7LL
#undef apple_laf_JRSUIConstants_Size__mini
#define apple_laf_JRSUIConstants_Size__mini 1L
#undef apple_laf_JRSUIConstants_Size__small
#define apple_laf_JRSUIConstants_Size__small 2L
#undef apple_laf_JRSUIConstants_Size__regular
#define apple_laf_JRSUIConstants_Size__regular 3L
#undef apple_laf_JRSUIConstants_Size__large
#define apple_laf_JRSUIConstants_Size__large 4L
#ifdef __cplusplus
}
#endif
#endif
