/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_WindowType */

#ifndef _Included_apple_laf_JRSUIConstants_WindowType
#define _Included_apple_laf_JRSUIConstants_WindowType
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_WindowType_SHIFT
#define apple_laf_JRSUIConstants_WindowType_SHIFT 28L
#undef apple_laf_JRSUIConstants_WindowType_SIZE
#define apple_laf_JRSUIConstants_WindowType_SIZE 2L
#undef apple_laf_JRSUIConstants_WindowType_MASK
#define apple_laf_JRSUIConstants_WindowType_MASK 805306368LL
#undef apple_laf_JRSUIConstants_WindowType__document
#define apple_laf_JRSUIConstants_WindowType__document 1L
#undef apple_laf_JRSUIConstants_WindowType__utility
#define apple_laf_JRSUIConstants_WindowType__utility 2L
#undef apple_laf_JRSUIConstants_WindowType__titlelessUtility
#define apple_laf_JRSUIConstants_WindowType__titlelessUtility 3L
#ifdef __cplusplus
}
#endif
#endif
