/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_NoIndicator */

#ifndef _Included_apple_laf_JRSUIConstants_NoIndicator
#define _Included_apple_laf_JRSUIConstants_NoIndicator
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_NoIndicator_SHIFT
#define apple_laf_JRSUIConstants_NoIndicator_SHIFT 32L
#undef apple_laf_JRSUIConstants_NoIndicator_SIZE
#define apple_laf_JRSUIConstants_NoIndicator_SIZE 1L
#undef apple_laf_JRSUIConstants_NoIndicator_MASK
#define apple_laf_JRSUIConstants_NoIndicator_MASK 4294967296LL
#undef apple_laf_JRSUIConstants_NoIndicator__no
#define apple_laf_JRSUIConstants_NoIndicator__no 0L
#undef apple_laf_JRSUIConstants_NoIndicator__yes
#define apple_laf_JRSUIConstants_NoIndicator__yes 1L
#ifdef __cplusplus
}
#endif
#endif
