/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_ShowArrows */

#ifndef _Included_apple_laf_JRSUIConstants_ShowArrows
#define _Included_apple_laf_JRSUIConstants_ShowArrows
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_ShowArrows_SHIFT
#define apple_laf_JRSUIConstants_ShowArrows_SHIFT 40L
#undef apple_laf_JRSUIConstants_ShowArrows_SIZE
#define apple_laf_JRSUIConstants_ShowArrows_SIZE 1L
#undef apple_laf_JRSUIConstants_ShowArrows_MASK
#define apple_laf_JRSUIConstants_ShowArrows_MASK 1099511627776LL
#undef apple_laf_JRSUIConstants_ShowArrows__no
#define apple_laf_JRSUIConstants_ShowArrows__no 0L
#undef apple_laf_JRSUIConstants_ShowArrows__yes
#define apple_laf_JRSUIConstants_ShowArrows__yes 1L
#ifdef __cplusplus
}
#endif
#endif
