/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apple_laf_JRSUIConstants_Animating */

#ifndef _Included_apple_laf_JRSUIConstants_Animating
#define _Included_apple_laf_JRSUIConstants_Animating
#ifdef __cplusplus
extern "C" {
#endif
#undef apple_laf_JRSUIConstants_Animating_SHIFT
#define apple_laf_JRSUIConstants_Animating_SHIFT 42L
#undef apple_laf_JRSUIConstants_Animating_SIZE
#define apple_laf_JRSUIConstants_Animating_SIZE 1L
#undef apple_laf_JRSUIConstants_Animating_MASK
#define apple_laf_JRSUIConstants_Animating_MASK 4398046511104LL
#undef apple_laf_JRSUIConstants_Animating__no
#define apple_laf_JRSUIConstants_Animating__no 0L
#undef apple_laf_JRSUIConstants_Animating__yes
#define apple_laf_JRSUIConstants_Animating__yes 1L
#ifdef __cplusplus
}
#endif
#endif
