package sun.nio.fs;              

class UnixConstants {

    static final int O_RDONLY;
    static final int O_WRONLY;
    static final int O_RDWR;
    static final int O_APPEND;
    static final int O_CREAT;
    static final int O_EXCL;
    static final int O_TRUNC;
    static final int O_SYNC;
    static final int O_DSYNC;
    static final int O_NOFOLLOW;
    static final int S_IAMB;
    static final int S_IRUSR;
    static final int S_IWUSR;
    static final int S_IXUSR;
    static final int S_IRGRP;
    static final int S_IWGRP;
    static final int S_IXGRP;
    static final int S_IROTH;
    static final int S_IWOTH;
    static final int S_IXOTH;
    static final int S_IFMT;
    static final int S_IFREG;
    static final int S_IFDIR;
    static final int S_IFLNK;
    static final int S_IFCHR;
    static final int S_IFBLK;
    static final int S_IFIFO;
    static final int R_OK;
    static final int W_OK;
    static final int X_OK;
    static final int F_OK;
    static final int ENOENT;
    static final int EACCES;
    static final int EEXIST;
    static final int ENOTDIR;
    static final int EINVAL;
    static final int EXDEV;
    static final int EISDIR;
    static final int ENOTEMPTY;
    static final int ENOSPC;
    static final int EAGAIN;
    static final int ENOSYS;
    static final int ELOOP;
    static final int EROFS;
    static final int ENODATA;
    static final int ERANGE;
    static final int EMFILE;
    static final int AT_SYMLINK_NOFOLLOW;
    static final int AT_REMOVEDIR;

    static {
        if (cli.IKVM.Runtime.RuntimeUtil.get_IsLinux()) {
            O_RDONLY = 0;
            O_WRONLY = 1;
            O_RDWR = 2;
            O_APPEND = 0x400;
            O_CREAT = 0x40;
            O_EXCL = 0x80;
            O_TRUNC = 0x200;
            O_SYNC = 0x1000;
            O_DSYNC = 0x1000;
            O_NOFOLLOW = 0x20000;
            S_IAMB = 0x1ff;
            S_IRUSR = 256;
            S_IWUSR = 128;
            S_IXUSR = 64;
            S_IRGRP = 32;
            S_IWGRP = 16;
            S_IXGRP = 8;
            S_IROTH = 4;
            S_IWOTH = 2;
            S_IXOTH = 1;
            S_IFMT = 0xf000;
            S_IFREG = 0x8000;
            S_IFDIR = 0x4000;
            S_IFLNK = 0xa000;
            S_IFCHR = 0x2000;
            S_IFBLK = 0x6000;
            S_IFIFO = 0x1000;
            R_OK = 4;
            W_OK = 2;
            X_OK = 1;
            F_OK = 0;
            ENOENT = 2;
            EACCES = 13;
            EEXIST = 17;
            ENOTDIR = 20;
            EINVAL = 22;
            EXDEV = 18;
            EISDIR = 21;
            ENOTEMPTY = 39;
            ENOSPC = 28;
            EAGAIN = 11;
            ENOSYS = 38;
            ELOOP = 40;
            EROFS = 30;
            ENODATA = 61;
            ERANGE = 34;
            EMFILE = 24;
            AT_SYMLINK_NOFOLLOW = 0x100;
            AT_REMOVEDIR = 0x200;
        } else {
            O_RDONLY = 0;
            O_WRONLY = 0;
            O_RDWR = 0;
            O_APPEND = 0;
            O_CREAT = 0;
            O_EXCL = 0;
            O_TRUNC = 0;
            O_SYNC = 0;
            O_DSYNC = 0;
            O_NOFOLLOW = 0;
            S_IAMB = 0;
            S_IRUSR = 0;
            S_IWUSR = 0;
            S_IXUSR = 0;
            S_IRGRP = 0;
            S_IWGRP = 0;
            S_IXGRP = 0;
            S_IROTH = 0;
            S_IWOTH = 0;
            S_IXOTH = 0;
            S_IFMT = 0;
            S_IFREG = 0;
            S_IFDIR = 0;
            S_IFLNK = 0;
            S_IFCHR = 0;
            S_IFBLK = 0;
            S_IFIFO = 0;
            R_OK = 0;
            W_OK = 0;
            X_OK = 0;
            F_OK = 0;
            ENOENT = 0;
            EACCES = 0;
            EEXIST = 0;
            ENOTDIR = 0;
            EINVAL = 0;
            EXDEV = 0;
            EISDIR = 0;
            ENOTEMPTY = 0;
            ENOSPC = 0;
            EAGAIN = 0;
            ENOSYS = 0;
            ELOOP = 0;
            EROFS = 0;
            ENODATA = 0;
            ERANGE = 0;
            EMFILE = 0;
            AT_SYMLINK_NOFOLLOW = 0;
            AT_REMOVEDIR = 0;
        }
    }

}                                                                              
