//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IKVM.MSBuild.Tasks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IKVM.MSBuild.Tasks.Resources.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0001: The IkvmReference {0} contains a circular reference..
        /// </summary>
        internal static string Error_IkvmCircularReference {
            get {
                return ResourceManager.GetString("Error.IkvmCircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0004: The IkvmReference {0} has invalid AssemblyName &apos;{1}&apos; or AssemblyVersion &apos;{2}&apos;..
        /// </summary>
        internal static string Error_IkvmInvalidAssemblyInfo {
            get {
                return ResourceManager.GetString("Error.IkvmInvalidAssemblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0002: The IkvmReference {0} has invalid AssemblyName &apos;{1}&apos;..
        /// </summary>
        internal static string Error_IkvmInvalidAssemblyName {
            get {
                return ResourceManager.GetString("Error.IkvmInvalidAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0003: The IkvmReference {0} has invalid AssemblyVersion &apos;{1}&apos;..
        /// </summary>
        internal static string Error_IkvmInvalidAssemblyVersion {
            get {
                return ResourceManager.GetString("Error.IkvmInvalidAssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0005: The IkvmReference {0} has an invalid Compile item &apos;{1}&apos;. Can only include jar or class files..
        /// </summary>
        internal static string Error_IkvmInvalidCompile {
            get {
                return ResourceManager.GetString("Error.IkvmInvalidCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0006: The IkvmReference {0} contains an invalid Reference &apos;{1}&apos;..
        /// </summary>
        internal static string Error_IkvmInvalidReference {
            get {
                return ResourceManager.GetString("Error.IkvmInvalidReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0007: The IkvmReference {0} has an invalid Sources item &apos;{1}&apos;. Can only include .java files..
        /// </summary>
        internal static string Error_IkvmInvalidSources {
            get {
                return ResourceManager.GetString("Error.IkvmInvalidSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0013: The IkvmReference {0} is missing AssemblyFileVersion..
        /// </summary>
        internal static string Error_IkvmMissingAssemblyFileVersion {
            get {
                return ResourceManager.GetString("Error.IkvmMissingAssemblyFileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0011: The IkvmReference {0} is missing AssemblyName..
        /// </summary>
        internal static string Error_IkvmMissingAssemblyName {
            get {
                return ResourceManager.GetString("Error.IkvmMissingAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0012: The IkvmReference {0} is missing AssemblyVersion..
        /// </summary>
        internal static string Error_IkvmMissingAssemblyVersion {
            get {
                return ResourceManager.GetString("Error.IkvmMissingAssemblyVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0008: The IkvmReference {0} is missing the Compile item &apos;{1}&apos;..
        /// </summary>
        internal static string Error_IkvmMissingCompile {
            get {
                return ResourceManager.GetString("Error.IkvmMissingCompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0009: The IkvmReference {0} is missing the Source item &apos;{1}&apos;..
        /// </summary>
        internal static string Error_IkvmMissingSources {
            get {
                return ResourceManager.GetString("Error.IkvmMissingSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IKVMSDK0010: The IkvmReference {0} requires at least one Compile item..
        /// </summary>
        internal static string Error_IkvmRequiresCompile {
            get {
                return ResourceManager.GetString("Error.IkvmRequiresCompile", resourceCulture);
            }
        }
    }
}
